Fix test reports

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,13 +28,11 @@ jobs:
       run: sbt -v compileDocumentation
     - name: Test
       run: sbt -v test
-    - name: Test Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure() # run regardless previous step succeeded or failed
+    - uses: actions/upload-artifact@v3  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
       with:
-        name: 'Tests results'
+        name: 'tests-results-${{ matrix.scala-version }}-${{ matrix.target-platform }}-${{ matrix.java }}'
         path: '**/test-reports/TEST*.xml'
-        reporter: java-junit
 
   publish:
     name: Publish release
